# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  OpsCore_config = debug
  Sandbox_config = debug
  Glad_config = debug
  GLFW_config = debug
  ImGui_config = debug
endif
ifeq ($(config),release)
  OpsCore_config = release
  Sandbox_config = release
  Glad_config = release
  GLFW_config = release
  ImGui_config = release
endif
ifeq ($(config),dist)
  OpsCore_config = dist
  Sandbox_config = dist
  Glad_config = dist
  GLFW_config = dist
  ImGui_config = dist
endif

PROJECTS := OpsCore Sandbox Glad GLFW ImGui

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

OpsCore: GLFW Glad ImGui
ifneq (,$(OpsCore_config))
	@echo "==== Building OpsCore ($(OpsCore_config)) ===="
	@${MAKE} --no-print-directory -C OpsCore -f Makefile config=$(OpsCore_config)
endif

Sandbox: GLFW Glad ImGui OpsCore
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C . -f Glad.make config=$(Glad_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C . -f GLFW.make config=$(GLFW_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C . -f ImGui.make config=$(ImGui_config)
endif

clean:
	@${MAKE} --no-print-directory -C OpsCore -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean
	@${MAKE} --no-print-directory -C . -f Glad.make clean
	@${MAKE} --no-print-directory -C . -f GLFW.make clean
	@${MAKE} --no-print-directory -C . -f ImGui.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   OpsCore"
	@echo "   Sandbox"
	@echo "   Glad"
	@echo "   GLFW"
	@echo "   ImGui"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"